/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../services/websocket/connectStatusSocket`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/websocket/WebSocketProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/websocket/WebSocketContext`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/websocket/useWebSocket`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/statistics` | `/statistics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/temperature` | `/temperature`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../services/websocket/connectStatusSocket`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/websocket/WebSocketProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/websocket/WebSocketContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/websocket/useWebSocket`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/statistics` | `/statistics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/temperature` | `/temperature`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../services/websocket/connectStatusSocket${`?${string}` | `#${string}` | ''}` | `/../contexts/websocket/WebSocketProvider${`?${string}` | `#${string}` | ''}` | `/../contexts/websocket/WebSocketContext${`?${string}` | `#${string}` | ''}` | `/../contexts/websocket/useWebSocket${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/statistics${`?${string}` | `#${string}` | ''}` | `/statistics${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/temperature${`?${string}` | `#${string}` | ''}` | `/temperature${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../services/websocket/connectStatusSocket`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/websocket/WebSocketProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/websocket/WebSocketContext`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/websocket/useWebSocket`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/statistics` | `/statistics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/temperature` | `/temperature`; params?: Router.UnknownInputParams; };
    }
  }
}
